// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Request.proto

package chatroom.common.serialization;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chatroom.common.serialization.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string uid = 1;</code>
   */
  java.lang.String getUid();
  /**
   * <code>string uid = 1;</code>
   */
  com.google.protobuf.ByteString
      getUidBytes();

  /**
   * <code>string msg = 2;</code>
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 2;</code>
   */
  com.google.protobuf.ByteString
      getMsgBytes();

  /**
   * <code>string date = 3;</code>
   */
  java.lang.String getDate();
  /**
   * <code>string date = 3;</code>
   */
  com.google.protobuf.ByteString
      getDateBytes();
}
