// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Request.proto

package chatroom.common.serialization;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chatroom.common.serialization.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.chatroom.common.serialization.Message message = 1;</code>
   */
  boolean hasMessage();
  /**
   * <code>.chatroom.common.serialization.Message message = 1;</code>
   */
  chatroom.common.serialization.Message getMessage();
  /**
   * <code>.chatroom.common.serialization.Message message = 1;</code>
   */
  chatroom.common.serialization.MessageOrBuilder getMessageOrBuilder();

  /**
   * <code>int32 code = 2;</code>
   */
  int getCode();
}
